name: 'pjt02_subscription'

profile: 'pjt02_subscription'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets: 
  - "target"
  - "dbt_packages"

models:
  pjt02_subscription:
    staging: 
      +materialized: view
    intermediate:
      fact:
        +materialized: view
    marts:
      +materialized: table